// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeVmmFfSFGx3qJycI5e0jGGN7CTh7twnM',
    appId: '1:965606173654:web:d1379be8e4ff465170d277',
    messagingSenderId: '965606173654',
    projectId: 'ilac-cebimde',
    authDomain: 'ilac-cebimde.firebaseapp.com',
    storageBucket: 'ilac-cebimde.firebasestorage.app',
    measurementId: 'G-KQ0R0W6EBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyM8KjuerB6duA8UP2OBThHjQUX18gBPw',
    appId: '1:965606173654:android:071a494f27d64f0a70d277',
    messagingSenderId: '965606173654',
    projectId: 'ilac-cebimde',
    storageBucket: 'ilac-cebimde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBATQAETjUhMVEbgtYHP-OAYWK6Aia2Fig',
    appId: '1:965606173654:ios:380f94485dbea48470d277',
    messagingSenderId: '965606173654',
    projectId: 'ilac-cebimde',
    storageBucket: 'ilac-cebimde.firebasestorage.app',
    iosBundleId: 'com.example.ilacimCebimde',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBATQAETjUhMVEbgtYHP-OAYWK6Aia2Fig',
    appId: '1:965606173654:ios:380f94485dbea48470d277',
    messagingSenderId: '965606173654',
    projectId: 'ilac-cebimde',
    storageBucket: 'ilac-cebimde.firebasestorage.app',
    iosBundleId: 'com.example.ilacimCebimde',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeVmmFfSFGx3qJycI5e0jGGN7CTh7twnM',
    appId: '1:965606173654:web:e885a8f75432b13f70d277',
    messagingSenderId: '965606173654',
    projectId: 'ilac-cebimde',
    authDomain: 'ilac-cebimde.firebaseapp.com',
    storageBucket: 'ilac-cebimde.firebasestorage.app',
    measurementId: 'G-Z5Q2XMYDR5',
  );

}